# Variables

@baseUrl = http://localhost:3333

# Login
# @name login
POST {{ baseUrl }}/login
Accept: application/json
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password":"1234"
}
